#!/bin/bash

echo "🚀 客服系统功能测试指南"
echo "========================"
echo ""
echo "服务已启动:"
echo "- Rust后端: http://localhost:6006"
echo "- 客服端开发服务器: http://localhost:6005"
echo ""
echo "测试步骤:"
echo ""
echo "1. 访问客服端 (开发模式):"
echo "   http://localhost:6005/kefu/"
echo "   - 点击'查看测试账号'"
echo "   - 选择 kefu001 (密码: 123456)"
echo "   - 点击'使用此账号'登录"
echo ""
echo "2. 访问客户端:"
echo "   http://localhost:6006/kehu"
echo "   - 等待连接建立"
echo "   - 发送测试消息"
echo ""
echo "3. 检查功能:"
echo "   - 客服端应该收到新客户通知"
echo "   - 双方应该能够实时通信"
echo ""
echo "按 Ctrl+C 结束测试"